CREATE TABLE courses (
    id INT PRIMARY KEY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    is_paid BOOLEAN NOT NULL,
    num_subscribers INT NOT NULL,
    avg_rating NUMERIC(3,2) NOT NULL,
    avg_rating_recent NUMERIC(3,2) NOT NULL,
    rating NUMERIC(3,2) NOT NULL,
    num_reviews INT NOT NULL,
    is_wishlisted BOOLEAN NOT NULL,
    num_published_lectures INT NOT NULL,
    num_published_practice_tests INT NOT NULL,
    created TIMESTAMP NOT NULL,
    published_time TIMESTAMP NOT NULL,
    discount_price_amount NUMERIC(10,2),
    discount_price_currency TEXT,
    discount_price_price_string TEXT,
    price_detail_amount NUMERIC(10,2) NOT NULL,
    price_detail_currency TEXT NOT NULL,
    price_detail_price_string TEXT NOT NULL
);

CREATE TABLE fact_udemy (
    id INT PRIMARY KEY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    is_paid BOOLEAN NOT NULL,
    num_subscribers INT NOT NULL,
    avg_rating NUMERIC(3,2) NOT NULL,
    avg_rating_recent NUMERIC(3,2) NOT NULL,
    rating NUMERIC(3,2) NOT NULL,
    num_reviews INT NOT NULL,
    is_wishlisted BOOLEAN NOT NULL,
    num_published_lectures INT NOT NULL,
    num_published_practice_tests INT NOT NULL,
    created date,
    published_time date,
    discount_price_amount NUMERIC(10,2),
    price_detail_amount NUMERIC(10,2) NOT NULL
);