CREATE TABLE data_amazon(
   index INT,
   order_id TEXT, 
   date TEXT, 
   status TEXT, 
   fulfilment TEXT, 
   sales_channel TEXT,
   ship_service_level TEXT, 
   style TEXT, 
   sku TEXT, 
   category TEXT,  
   size TEXT, 
   asin TEXT,
   courier_status TEXT, 
   qty INT, 
   currency TEXT, 
   amount FLOAT, 
   ship_city TEXT,
   ship_state TEXT, 
   ship_postal_code FLOAT, 
   ship_country TEXT, 
   promotion_ids TEXT,
   b2b BOOLEAN, 
   fulfilled_by TEXT
)